# Generated by Django 4.2.1 on 2023-05-08 00:45

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('featured_image', models.ImageField(upload_to='Course Images')),
                ('author', models.CharField(max_length=100)),
                ('number_of_lectures', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('earth', 'earth'), ('business', 'business'), ('health', 'health'), ('technology', 'technology'), ('law', 'law'), ('marine', 'marine'), ('nationalism', 'nationalism')], max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=200)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video_link', models.CharField(max_length=900)),
                ('description', models.TextField()),
                ('serial_number', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
            ],
        ),
    ]
