# Generated by Django 4.2.1 on 2023-05-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(help_text='Upload an image with a resolution of 3000x2000', upload_to='Course Images'),
        ),
    ]
